coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 1%  # Allow 1% drop before failing
    patch:
      default:
        target: 60%  # New code should have 60%+ coverage

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
