// Weapon type definitions
export interface Weapon {
  id: number;
  name: string;
  category: WeaponCategory;
  damage: number;
  cooldown: number;
  projectileSpeed: number;
  projectileSize: {
    width: number;
    height: number;
  };
  price: number;
  emoji: string;
  description: string;
  projectileColor: string;
}

export type WeaponCategory = 'ballistic' | 'fire' | 'laser' | 'explosive';

export const WEAPONS: Weapon[] = [
  // ─── Ballistic (IDs 1-20) ───────────────────────────────────────────────────
  {
    id: 1,
    name: 'Pistol',
    category: 'ballistic',
    damage: 5,
    cooldown: 30,
    projectileSpeed: 8,
    projectileSize: { width: 8, height: 4 },
    price: 50,
    emoji: '🔫',
    description: 'A humble sidearm that gets the job done.',
    projectileColor: '#FFD700',
  },
  {
    id: 2,
    name: 'Revolver',
    category: 'ballistic',
    damage: 7,
    cooldown: 28,
    projectileSpeed: 9,
    projectileSize: { width: 8, height: 4 },
    price: 313,
    emoji: '🔫',
    description: 'Six shots of old-school stopping power.',
    projectileColor: '#FFD000',
  },
  {
    id: 3,
    name: 'Desert Eagle',
    category: 'ballistic',
    damage: 10,
    cooldown: 27,
    projectileSpeed: 9,
    projectileSize: { width: 8, height: 4 },
    price: 576,
    emoji: '🔫',
    description: 'Heavy and loud — every shot commands respect.',
    projectileColor: '#FFCA00',
  },
  {
    id: 4,
    name: 'Shotgun',
    category: 'ballistic',
    damage: 12,
    cooldown: 25,
    projectileSpeed: 10,
    projectileSize: { width: 9, height: 4 },
    price: 839,
    emoji: '🔫',
    description: 'Spread of lead at close range.',
    projectileColor: '#FFC400',
  },
  {
    id: 5,
    name: 'Sawed-Off',
    category: 'ballistic',
    damage: 14,
    cooldown: 24,
    projectileSpeed: 10,
    projectileSize: { width: 9, height: 4 },
    price: 1103,
    emoji: '🔫',
    description: 'Compact chaos in a shortened barrel.',
    projectileColor: '#FFBE00',
  },
  {
    id: 6,
    name: 'Double Barrel',
    category: 'ballistic',
    damage: 16,
    cooldown: 22,
    projectileSpeed: 10,
    projectileSize: { width: 9, height: 4 },
    price: 1366,
    emoji: '🔫',
    description: 'Two barrels mean twice the boom.',
    projectileColor: '#FFB800',
  },
  {
    id: 7,
    name: 'SMG',
    category: 'ballistic',
    damage: 18,
    cooldown: 21,
    projectileSpeed: 11,
    projectileSize: { width: 9, height: 4 },
    price: 1629,
    emoji: '🔫',
    description: 'Rapid fire in a compact package.',
    projectileColor: '#FFB200',
  },
  {
    id: 8,
    name: 'UZI',
    category: 'ballistic',
    damage: 20,
    cooldown: 20,
    projectileSpeed: 11,
    projectileSize: { width: 9, height: 4 },
    price: 1892,
    emoji: '🔫',
    description: 'Israeli engineering, devastating speed.',
    projectileColor: '#FFAC00',
  },
  {
    id: 9,
    name: 'MP5',
    category: 'ballistic',
    damage: 22,
    cooldown: 19,
    projectileSpeed: 12,
    projectileSize: { width: 9, height: 4 },
    price: 2155,
    emoji: '🔫',
    description: 'Precise bursts from a tactical classic.',
    projectileColor: '#FFA600',
  },
  {
    id: 10,
    name: 'P90',
    category: 'ballistic',
    damage: 24,
    cooldown: 17,
    projectileSpeed: 12,
    projectileSize: { width: 10, height: 4 },
    price: 2418,
    emoji: '🔫',
    description: 'Futuristic bullpup that never stops firing.',
    projectileColor: '#FFA000',
  },
  {
    id: 11,
    name: 'AK-47',
    category: 'ballistic',
    damage: 27,
    cooldown: 16,
    projectileSpeed: 13,
    projectileSize: { width: 10, height: 4 },
    price: 2682,
    emoji: '🔫',
    description: 'The world\'s most reliable assault rifle.',
    projectileColor: '#FF9A00',
  },
  {
    id: 12,
    name: 'M16',
    category: 'ballistic',
    damage: 29,
    cooldown: 15,
    projectileSpeed: 14,
    projectileSize: { width: 10, height: 5 },
    price: 2945,
    emoji: '🔫',
    description: 'American-made three-round burst precision.',
    projectileColor: '#FF9400',
  },
  {
    id: 13,
    name: 'AR-15',
    category: 'ballistic',
    damage: 31,
    cooldown: 13,
    projectileSpeed: 14,
    projectileSize: { width: 10, height: 5 },
    price: 3208,
    emoji: '🔫',
    description: 'Semi-auto workhorse with modular adaptability.',
    projectileColor: '#FF8E00',
  },
  {
    id: 14,
    name: 'SCAR',
    category: 'ballistic',
    damage: 33,
    cooldown: 12,
    projectileSpeed: 15,
    projectileSize: { width: 10, height: 5 },
    price: 3471,
    emoji: '🔫',
    description: 'Special ops grade rifle, leaves a mark.',
    projectileColor: '#FF8800',
  },
  {
    id: 15,
    name: 'M4A1',
    category: 'ballistic',
    damage: 35,
    cooldown: 11,
    projectileSpeed: 15,
    projectileSize: { width: 11, height: 5 },
    price: 3734,
    emoji: '🔫',
    description: 'Military carbine balancing speed and power.',
    projectileColor: '#FF8400',
  },
  {
    id: 16,
    name: 'LMG',
    category: 'ballistic',
    damage: 38,
    cooldown: 10,
    projectileSpeed: 16,
    projectileSize: { width: 11, height: 5 },
    price: 3997,
    emoji: '🔫',
    description: 'Light machine gun that suppresses everything.',
    projectileColor: '#FF8000',
  },
  {
    id: 17,
    name: 'Minigun',
    category: 'ballistic',
    damage: 40,
    cooldown: 9,
    projectileSpeed: 17,
    projectileSize: { width: 11, height: 5 },
    price: 4260,
    emoji: '🔫',
    description: 'Spinning barrels unleash a wall of lead.',
    projectileColor: '#FF7C00',
  },
  {
    id: 18,
    name: 'Gatling Gun',
    category: 'ballistic',
    damage: 42,
    cooldown: 8,
    projectileSpeed: 18,
    projectileSize: { width: 11, height: 5 },
    price: 4524,
    emoji: '🔫',
    description: 'The original rapid-fire war machine.',
    projectileColor: '#FF7800',
  },
  {
    id: 19,
    name: 'Sniper Rifle',
    category: 'ballistic',
    damage: 45,
    cooldown: 6,
    projectileSpeed: 19,
    projectileSize: { width: 12, height: 5 },
    price: 4787,
    emoji: '🔫',
    description: 'One shot across the map, one kill.',
    projectileColor: '#FF7400',
  },
  {
    id: 20,
    name: 'Barrett .50 Cal',
    category: 'ballistic',
    damage: 50,
    cooldown: 5,
    projectileSpeed: 20,
    projectileSize: { width: 12, height: 5 },
    price: 5000,
    emoji: '🔫',
    description: 'Anti-material rifle that stops tanks cold.',
    projectileColor: '#FF8C00',
  },

  // ─── Fire (IDs 21-30) ────────────────────────────────────────────────────────
  {
    id: 21,
    name: 'Match',
    category: 'fire',
    damage: 8,
    cooldown: 25,
    projectileSpeed: 6,
    projectileSize: { width: 10, height: 6 },
    price: 100,
    emoji: '🔥',
    description: 'A single tiny flame that still stings.',
    projectileColor: '#FF4500',
  },
  {
    id: 22,
    name: 'Torch',
    category: 'fire',
    damage: 13,
    cooldown: 23,
    projectileSpeed: 7,
    projectileSize: { width: 11, height: 7 },
    price: 766,
    emoji: '🔦',
    description: 'A blazing torch hurled with fiery intent.',
    projectileColor: '#FF4D00',
  },
  {
    id: 23,
    name: 'Flare Gun',
    category: 'fire',
    damage: 17,
    cooldown: 21,
    projectileSpeed: 8,
    projectileSize: { width: 12, height: 7 },
    price: 1433,
    emoji: '🔫',
    description: 'Distress signal repurposed as a weapon.',
    projectileColor: '#FF5500',
  },
  {
    id: 24,
    name: 'Molotov',
    category: 'fire',
    damage: 22,
    cooldown: 19,
    projectileSpeed: 9,
    projectileSize: { width: 13, height: 8 },
    price: 2100,
    emoji: '🍾',
    description: 'A bottle of burning improvised destruction.',
    projectileColor: '#FF5D00',
  },
  {
    id: 25,
    name: 'Flame Pistol',
    category: 'fire',
    damage: 26,
    cooldown: 17,
    projectileSpeed: 10,
    projectileSize: { width: 14, height: 8 },
    price: 2766,
    emoji: '🔥',
    description: 'Compact sidearm that spits short bursts of fire.',
    projectileColor: '#FF6600',
  },
  {
    id: 26,
    name: 'Flamethrower',
    category: 'fire',
    damage: 30,
    cooldown: 16,
    projectileSpeed: 11,
    projectileSize: { width: 15, height: 9 },
    price: 3433,
    emoji: '🔥',
    description: 'Sustained stream of burning napalm.',
    projectileColor: '#FF6300',
  },
  {
    id: 27,
    name: 'Napalm Sprayer',
    category: 'fire',
    damage: 35,
    cooldown: 14,
    projectileSpeed: 12,
    projectileSize: { width: 16, height: 10 },
    price: 4100,
    emoji: '🔥',
    description: 'Sticky burning gel coats everything it touches.',
    projectileColor: '#FF3D00',
  },
  {
    id: 28,
    name: 'Dragon\'s Breath',
    category: 'fire',
    damage: 43,
    cooldown: 12,
    projectileSpeed: 13,
    projectileSize: { width: 17, height: 10 },
    price: 4766,
    emoji: '🐉',
    description: 'Mythical flames with a devastating reach.',
    projectileColor: '#FF2800',
  },
  {
    id: 29,
    name: 'Phoenix Cannon',
    category: 'fire',
    damage: 51,
    cooldown: 10,
    projectileSpeed: 14,
    projectileSize: { width: 18, height: 11 },
    price: 5433,
    emoji: '🦅',
    description: 'Reborn from ash, fires an inferno bolt.',
    projectileColor: '#FF1400',
  },
  {
    id: 30,
    name: 'Inferno Core',
    category: 'fire',
    damage: 60,
    cooldown: 8,
    projectileSpeed: 15,
    projectileSize: { width: 20, height: 12 },
    price: 6000,
    emoji: '💥',
    description: 'A concentrated core of pure hellfire energy.',
    projectileColor: '#FF0000',
  },

  // ─── Laser (IDs 31-40) ───────────────────────────────────────────────────────
  {
    id: 31,
    name: 'Flashlight',
    category: 'laser',
    damage: 10,
    cooldown: 20,
    projectileSpeed: 12,
    projectileSize: { width: 16, height: 3 },
    price: 150,
    emoji: '🔦',
    description: 'More weapon than flashlight at this setting.',
    projectileColor: '#00FFFF',
  },
  {
    id: 32,
    name: 'Laser Pointer',
    category: 'laser',
    damage: 17,
    cooldown: 18,
    projectileSpeed: 13,
    projectileSize: { width: 17, height: 3 },
    price: 928,
    emoji: '🔴',
    description: 'Precision dot upgraded to a piercing beam.',
    projectileColor: '#00E5FF',
  },
  {
    id: 33,
    name: 'Light Pistol',
    category: 'laser',
    damage: 23,
    cooldown: 16,
    projectileSpeed: 14,
    projectileSize: { width: 18, height: 3 },
    price: 1705,
    emoji: '🔫',
    description: 'Compact photon emitter for rapid light attacks.',
    projectileColor: '#00CCFF',
  },
  {
    id: 34,
    name: 'Pulse Blaster',
    category: 'laser',
    damage: 30,
    cooldown: 15,
    projectileSpeed: 15,
    projectileSize: { width: 18, height: 3 },
    price: 2483,
    emoji: '⚡',
    description: 'Rhythmic energy pulses burn through defenses.',
    projectileColor: '#00AAFF',
  },
  {
    id: 35,
    name: 'Ion Beam',
    category: 'laser',
    damage: 37,
    cooldown: 13,
    projectileSpeed: 17,
    projectileSize: { width: 19, height: 4 },
    price: 3261,
    emoji: '⚡',
    description: 'Ionized beam strips matter at the molecular level.',
    projectileColor: '#3300FF',
  },
  {
    id: 36,
    name: 'Plasma Rifle',
    category: 'laser',
    damage: 43,
    cooldown: 11,
    projectileSpeed: 18,
    projectileSize: { width: 20, height: 4 },
    price: 4038,
    emoji: '🔮',
    description: 'Superheated plasma tears through armor.',
    projectileColor: '#8800FF',
  },
  {
    id: 37,
    name: 'Photon Cannon',
    category: 'laser',
    damage: 50,
    cooldown: 9,
    projectileSpeed: 20,
    projectileSize: { width: 21, height: 4 },
    price: 4816,
    emoji: '✨',
    description: 'Concentrated photon burst at the speed of light.',
    projectileColor: '#BB00FF',
  },
  {
    id: 38,
    name: 'Quantum Ray',
    category: 'laser',
    damage: 57,
    cooldown: 7,
    projectileSpeed: 22,
    projectileSize: { width: 22, height: 4 },
    price: 5594,
    emoji: '🌀',
    description: 'Quantum-entangled beam ignores conventional physics.',
    projectileColor: '#DD00FF',
  },
  {
    id: 39,
    name: 'Nova Beam',
    category: 'laser',
    damage: 63,
    cooldown: 5,
    projectileSpeed: 23,
    projectileSize: { width: 23, height: 5 },
    price: 6372,
    emoji: '💫',
    description: 'Stellar-energy beam harnessed into a weapon.',
    projectileColor: '#FF00FF',
  },
  {
    id: 40,
    name: 'Death Ray',
    category: 'laser',
    damage: 70,
    cooldown: 4,
    projectileSpeed: 25,
    projectileSize: { width: 24, height: 5 },
    price: 7000,
    emoji: '☠️',
    description: 'Ultimate laser that annihilates all in its path.',
    projectileColor: '#FFFFFF',
  },

  // ─── Explosive (IDs 41-50) ──────────────────────────────────────────────────
  {
    id: 41,
    name: 'Firecracker',
    category: 'explosive',
    damage: 15,
    cooldown: 60,
    projectileSpeed: 5,
    projectileSize: { width: 12, height: 12 },
    price: 200,
    emoji: '🧨',
    description: 'Loud, bright, and surprisingly painful.',
    projectileColor: '#FF6600',
  },
  {
    id: 42,
    name: 'Cherry Bomb',
    category: 'explosive',
    damage: 23,
    cooldown: 57,
    projectileSpeed: 6,
    projectileSize: { width: 13, height: 13 },
    price: 1311,
    emoji: '🍒',
    description: 'Small and cheerful — right up until it\'s not.',
    projectileColor: '#FF5C00',
  },
  {
    id: 43,
    name: 'Grenade',
    category: 'explosive',
    damage: 32,
    cooldown: 53,
    projectileSpeed: 7,
    projectileSize: { width: 13, height: 13 },
    price: 2422,
    emoji: '💣',
    description: 'Standard infantry grenade with lethal blast.',
    projectileColor: '#FF5200',
  },
  {
    id: 44,
    name: 'Pipe Bomb',
    category: 'explosive',
    damage: 40,
    cooldown: 50,
    projectileSpeed: 7,
    projectileSize: { width: 14, height: 14 },
    price: 3533,
    emoji: '🔧',
    description: 'Improvised but effective homemade explosive.',
    projectileColor: '#FF4800',
  },
  {
    id: 45,
    name: 'Dynamite Bundle',
    category: 'explosive',
    damage: 49,
    cooldown: 46,
    projectileSpeed: 8,
    projectileSize: { width: 15, height: 15 },
    price: 4644,
    emoji: '🧱',
    description: 'Classic demolition stick bundled for more bang.',
    projectileColor: '#FF3E00',
  },
  {
    id: 46,
    name: 'C4',
    category: 'explosive',
    damage: 57,
    cooldown: 43,
    projectileSpeed: 9,
    projectileSize: { width: 16, height: 16 },
    price: 5755,
    emoji: '💥',
    description: 'Military-grade plastic explosive, remote detonated.',
    projectileColor: '#FF3300',
  },
  {
    id: 47,
    name: 'RPG',
    category: 'explosive',
    damage: 66,
    cooldown: 39,
    projectileSpeed: 10,
    projectileSize: { width: 17, height: 17 },
    price: 6866,
    emoji: '🚀',
    description: 'Rocket-propelled grenade with massive punch.',
    projectileColor: '#CC1100',
  },
  {
    id: 48,
    name: 'Mortar',
    category: 'explosive',
    damage: 74,
    cooldown: 36,
    projectileSpeed: 10,
    projectileSize: { width: 18, height: 18 },
    price: 7977,
    emoji: '💣',
    description: 'High-arc shell that rains down devastation.',
    projectileColor: '#AA0000',
  },
  {
    id: 49,
    name: 'Missile Launcher',
    category: 'explosive',
    damage: 83,
    cooldown: 32,
    projectileSpeed: 11,
    projectileSize: { width: 19, height: 19 },
    price: 9088,
    emoji: '🚀',
    description: 'Lock-on missile delivers precise obliteration.',
    projectileColor: '#920000',
  },
  {
    id: 50,
    name: 'Nuclear Launcher',
    category: 'explosive',
    damage: 100,
    cooldown: 15,
    projectileSpeed: 12,
    projectileSize: { width: 20, height: 20 },
    price: 10000,
    emoji: '☢️',
    description: 'Miniature nuke — the ultimate prestige weapon.',
    projectileColor: '#8B0000',
  },
];

// Weapon categories
export const WEAPON_CATEGORIES: Array<{ id: WeaponCategory; name: string; emoji: string }> = [
  { id: 'ballistic', name: 'Ballistic', emoji: '🔫' },
  { id: 'fire', name: 'Fire', emoji: '🔥' },
  { id: 'laser', name: 'Laser', emoji: '⚡' },
  { id: 'explosive', name: 'Explosive', emoji: '💣' },
];

// Get weapon by ID
export const getWeaponById = (id: number): Weapon | undefined => {
  return WEAPONS.find((weapon) => weapon.id === id);
};

// Get weapons by category
export const getWeaponsByCategory = (category: WeaponCategory): Weapon[] => {
  return WEAPONS.filter((weapon) => weapon.category === category);
};
